import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import {
  Box, Collapse, Container, Flex, Grid, GridItem, Heading, HStack, Icon, Image,
  Text, VStack, useColorMode, useColorModeValue, Badge,
} from '@chakra-ui/react'
import {
  FaRocket, FaFolderOpen, FaCog, FaToggleOn, FaFileAlt,
  FaLaptopCode, FaPenFancy, FaBriefcase, FaFlask, FaBullhorn,
  FaUser, FaImage, FaTerminal, FaCloudUploadAlt, FaQuestionCircle,
  FaChevronDown, FaArrowLeft, FaFolder, FaFile, FaCode,
  FaLightbulb, FaRobot, FaGlobe,
} from 'react-icons/fa'
import { IconType } from 'react-icons'
import { terminalPalette } from '@/config/theme'

/* ── Types ────────────────────────────────────────────────────── */

type Block =
  | { type: 'text'; content: string }
  | { type: 'code'; content: string; label?: string }
  | { type: 'tip'; content: string }
  | { type: 'table'; content: string }
  | { type: 'steps'; steps: { title: string; desc: string }[] }
  | { type: 'fields'; fields: { name: string; required?: boolean; desc: string; example?: string }[] }
  | { type: 'filetree'; items: { name: string; isFolder?: boolean; desc?: string; depth: number }[] }
  | { type: 'toggles'; toggles: { name: string; desc: string; default: boolean }[] }

interface GuideSection {
  id: string
  icon: IconType
  accent: string
  title: string
  subtitle: string
  blocks: Block[]
}

/* ── Section data ─────────────────────────────────────────────── */

const sections: GuideSection[] = [
  {
    id: 'quickstart',
    icon: FaRocket,
    accent: '#88c0d0',
    title: 'Quick Start',
    subtitle: 'Get your portfolio running in 3 steps',
    blocks: [
      { type: 'steps', steps: [
        { title: 'Install dependencies', desc: 'Open a terminal in your project folder and install all required packages.' },
        { title: 'Run the setup wizard', desc: 'The wizard asks your name, email, and social links, then generates your config file.' },
        { title: 'Start the dev server', desc: 'Opens your portfolio in the browser. Changes you make are reflected instantly.' },
      ] },
      { type: 'code', label: 'Terminal commands', content: `# 1. Install dependencies
npm install

# 2. Run the setup wizard (generates content/site.json)
npm run setup

# 3. Start dev server — opens http://localhost:5173
npm run dev` },
      { type: 'text', content: 'Before you start, make sure Node.js (v18+) and Git are installed. You can check by running node -v and git -v in your terminal.' },
      { type: 'tip', content: 'The setup wizard only creates site.json with your basic info. All other content files are ready to edit at your own pace.' },
    ],
  },
  {
    id: 'structure',
    icon: FaFolderOpen,
    accent: '#ebcb8b',
    title: 'Project Structure',
    subtitle: 'Where your content lives — you only edit one folder',
    blocks: [
      { type: 'text', content: 'Everything you need to edit is in the content/ folder. You never need to touch any code in src/.' },
      { type: 'filetree', items: [
        { name: 'content/', isFolder: true, desc: 'All your content goes here', depth: 0 },
        { name: 'site.json', desc: 'Name, contact, social, template, sections order, components', depth: 1 },
        { name: 'about.md', desc: 'Your bio text and career timeline (journeyPhases)', depth: 1 },
        { name: 'experience.json', desc: 'Work history and education', depth: 1 },
        { name: 'publications/', isFolder: true, desc: 'One file per paper', depth: 1 },
        { name: 'projects/', isFolder: true, desc: 'One file per project', depth: 1 },
        { name: 'articles/', isFolder: true, desc: 'One file per blog post', depth: 1 },
        { name: 'news.json', desc: 'Announcements and updates', depth: 1 },
        { name: 'awards.json', desc: 'Awards and honors', depth: 1 },
        { name: 'talks.json', desc: 'Talks and presentations', depth: 1 },
        { name: 'teaching.json', desc: 'Teaching and courses', depth: 1 },
        { name: 'research.json', desc: 'Research lab affiliations', depth: 1 },
        { name: 'logos.json', desc: 'Maps institution names to logo images', depth: 1 },
        { name: 'images/', isFolder: true, desc: 'Avatar, logos, paper figures, project screenshots', depth: 1 },
        { name: 'zh/', isFolder: true, desc: 'Chinese translations (same structure)', depth: 1 },
      ] },
      { type: 'tip', content: 'After setup, your workflow is: edit a file in content/ → save → browser auto-refreshes. That\'s it!' },
    ],
  },
  {
    id: 'site-config',
    icon: FaCog,
    accent: '#b48ead',
    title: 'Site Configuration',
    subtitle: 'Your master config file — name, contact, social links',
    blocks: [
      { type: 'text', content: 'site.json is the central config file generated by the setup wizard. Here are all the fields you can customize:' },
      { type: 'fields', fields: [
        { name: 'template', desc: 'Visual template to use', example: '"terminal"' },
        { name: 'sections', desc: 'Home page section order — reorder or remove items to customize layout', example: '["hero", "bio", "newsDisplay", ...]' },
        { name: 'components', desc: 'Override individual section variants', example: '{ "about": "timeline" }' },
        { name: 'name.full', required: true, desc: 'Your full display name', example: 'Alex Chen' },
        { name: 'name.first / last', required: true, desc: 'Used for terminal greeting and author matching', example: 'Alex / Chen' },
        { name: 'name.nickname', desc: 'Short name for casual display', example: 'Alex' },
        { name: 'contact.email', required: true, desc: 'Primary contact email', example: 'alex@example.com' },
        { name: 'contact.location', desc: 'City and country for display', example: 'Portland, OR, USA' },
        { name: 'social.github', desc: 'Full GitHub profile URL', example: 'https://github.com/username' },
        { name: 'social.linkedin', desc: 'Full LinkedIn profile URL' },
        { name: 'social.twitter', desc: 'Full Twitter/X profile URL' },
        { name: 'social.googleScholar', desc: 'Google Scholar profile URL' },
        { name: 'terminal.username', desc: 'Username shown in the terminal prompt', example: 'alex' },
        { name: 'terminal.skills', desc: 'Skill tags — string or { name, icon } objects', example: '[{ "name": "Python", "icon": "FaPython" }]' },
        { name: 'terminal.timezone', desc: 'Your timezone for the clock display', example: 'America/Los_Angeles' },
        { name: 'avatar', required: true, desc: 'Filename of your photo in content/images/', example: 'avatar.jpg' },
      ] },
      { type: 'code', label: 'Example site.json (abbreviated)', content: `{
  "template": "terminal",
  "sections": ["hero", "bio", "newsDisplay", "selectedPublications",
    "journey", "skills", "mentorship", "accomplishments", "contact", "footer"],
  "components": {},
  "name": { "full": "Alex Chen", "first": "Alex", "last": "Chen" },
  "contact": { "email": "alex@example.com", "location": "Portland, OR" },
  "social": { "github": "https://github.com/alexchen" },
  "terminal": {
    "username": "alex",
    "skills": [{ "name": "Python", "icon": "FaPython" }, { "name": "React", "icon": "FaReact" }]
  },
  "avatar": "avatar.jpg"
}` },
      { type: 'tip', content: 'You can re-run npm run setup anytime to regenerate this file from scratch.' },
    ],
  },
  {
    id: 'features',
    icon: FaToggleOn,
    accent: '#a3be8c',
    title: 'Feature Toggles',
    subtitle: 'Show or hide entire pages with one switch',
    blocks: [
      { type: 'text', content: 'Each feature can be turned on or off in the features section of site.json. When a feature is off, its page and navigation link are completely hidden.' },
      { type: 'toggles', toggles: [
        { name: 'publications', desc: 'Academic papers and research publications page', default: true },
        { name: 'projects', desc: 'Portfolio projects showcase page', default: true },
        { name: 'articles', desc: 'Blog posts and articles page', default: true },
        { name: 'experience', desc: 'Work history and education timeline page', default: true },
        { name: 'news', desc: 'News announcements on the home page', default: true },
        { name: 'pets', desc: 'Pet companion section on the home page', default: false },
        { name: 'guide', desc: 'This guide page (disable for your live portfolio)', default: false },
      ] },
      { type: 'text', content: 'Common presets to get started quickly:' },
      { type: 'table', content: `Preset|What to enable
Software developer|projects, experience, articles
Researcher / Academic|publications, experience, news, articles
Student / Job seeker|projects, experience, awards
Designer / Creative|projects, articles
Minimal|projects only` },
      { type: 'code', label: 'How it looks in site.json', content: `"features": {
  "publications": true,
  "projects": true,
  "articles": false,
  "experience": true,
  "news": true,
  "pets": false,
  "guide": false
}` },
    ],
  },
  {
    id: 'edit-publications',
    icon: FaFileAlt,
    accent: '#81a1c1',
    title: 'Edit Publications',
    subtitle: 'Add academic papers — one Markdown file per paper',
    blocks: [
      { type: 'text', content: 'Create a .md file in content/publications/ for each paper. The top section (between --- marks) contains structured data, the body is an optional description.' },
      { type: 'fields', fields: [
        { name: 'title', required: true, desc: 'Full paper title' },
        { name: 'authors', required: true, desc: 'Comma-separated author list (your name will be highlighted automatically)' },
        { name: 'venue', required: true, desc: 'Conference or journal name', example: 'NeurIPS 2025' },
        { name: 'year', required: true, desc: 'Publication year', example: '2025' },
        { name: 'type', desc: 'Paper type: conference, journal, workshop, preprint, or thesis' },
        { name: 'status', desc: 'Publication status: published, accepted, under-review, or preprint' },
        { name: 'award', desc: 'Award if any', example: 'Best Paper Award' },
        { name: 'links', desc: 'List of links — each needs text, url, and icon name' },
        { name: 'abstract', desc: 'Paper abstract (shown on click)' },
        { name: 'featuredImage', desc: 'Path to a figure image', example: '/images/paper-fig.png' },
        { name: 'tldr', desc: 'One-line plain-English summary' },
      ] },
      { type: 'code', label: 'Example: content/publications/my-paper.md', content: `---
title: "Efficient Transformers for Edge Devices"
authors: "Alex Chen, Jane Smith, Bob Park"
venue: "NeurIPS 2025"
year: 2025
type: conference
status: published
award: "Spotlight Paper"
links:
  - text: Paper
    url: https://arxiv.org/abs/xxxx
    icon: FaFilePdf
  - text: Code
    url: https://github.com/user/repo
    icon: FaGithub
tldr: "A 3x faster transformer that runs on mobile phones."
---

Optional longer description goes here. Supports **Markdown**.` },
      { type: 'tip', content: 'Your name is auto-highlighted in the author list based on the name variants in site.json. Add name variations to name.authorVariants if needed.' },
    ],
  },
  {
    id: 'edit-projects',
    icon: FaLaptopCode,
    accent: '#d08770',
    title: 'Edit Projects',
    subtitle: 'Showcase your portfolio work — one Markdown file per project',
    blocks: [
      { type: 'text', content: 'Create a .md file in content/projects/ for each project. The structure is similar to publications.' },
      { type: 'fields', fields: [
        { name: 'title', required: true, desc: 'Project name' },
        { name: 'description', required: true, desc: 'Short one-line description' },
        { name: 'tags', desc: 'Technology tags', example: 'React, Python, Docker' },
        { name: 'year', desc: 'Year of the project', example: '2025' },
        { name: 'links', desc: 'List of links (demo, GitHub, docs, etc.)' },
        { name: 'featured', desc: 'Set to true to highlight this project' },
        { name: 'featuredImage', desc: 'Path to a screenshot', example: '/images/projects/demo.png' },
      ] },
      { type: 'code', label: 'Example: content/projects/my-app.md', content: `---
title: "AI Study Buddy"
description: "An AI-powered study assistant for students."
tags: [React, OpenAI, Node.js]
year: 2025
featured: true
links:
  - text: Demo
    url: https://study-buddy.app
    icon: FaExternalLinkAlt
  - text: GitHub
    url: https://github.com/user/study-buddy
    icon: FaGithub
---

Longer description in Markdown. Explain what it does and why.` },
    ],
  },
  {
    id: 'edit-articles',
    icon: FaPenFancy,
    accent: '#bf616a',
    title: 'Edit Articles',
    subtitle: 'Write blog posts — one Markdown file per article',
    blocks: [
      { type: 'text', content: 'Create a .md file in content/articles/ for each blog post. Write the body in Markdown below the front matter.' },
      { type: 'fields', fields: [
        { name: 'title', required: true, desc: 'Article headline' },
        { name: 'date', required: true, desc: 'Publication date', example: '2025-03-01' },
        { name: 'tags', desc: 'Topic tags', example: 'AI, Tutorial, Python' },
        { name: 'description', desc: 'Short summary shown in article list' },
        { name: 'links', desc: 'External links (e.g. published on Medium)' },
      ] },
      { type: 'code', label: 'Example: content/articles/my-post.md', content: `---
title: "Getting Started with LLMs"
date: 2025-03-01
tags: [AI, Tutorial]
description: "A beginner-friendly guide to large language models."
links:
  - text: Read on Medium
    url: https://medium.com/@user/post
    icon: FaMedium
---

Your article body in **Markdown**. Use headings, lists, code blocks, etc.` },
    ],
  },
  {
    id: 'edit-experience',
    icon: FaBriefcase,
    accent: '#88c0d0',
    title: 'Edit Experience',
    subtitle: 'Work history and education in one JSON file',
    blocks: [
      { type: 'text', content: 'Edit content/experience.json to add your work positions, internships, and education history. Each entry is displayed on a visual timeline.' },
      { type: 'fields', fields: [
        { name: 'title', required: true, desc: 'Job title or degree name', example: 'Software Engineer' },
        { name: 'company', required: true, desc: 'Company or university name', example: 'Google' },
        { name: 'type', required: true, desc: 'Entry type: work, education, internship, or research' },
        { name: 'startDate', required: true, desc: 'Start date', example: '2023-09' },
        { name: 'endDate', desc: 'End date (leave empty for current position)', example: '2025-06' },
        { name: 'isCurrent', desc: 'Set to true for ongoing positions (shows "Present")' },
        { name: 'location', desc: 'City and state/country', example: 'San Francisco, CA' },
        { name: 'description', desc: 'Short description of your role' },
        { name: 'tags', desc: 'Skills and technologies used' },
      ] },
      { type: 'code', label: 'Example entry in experience.json', content: `{
  "title": "Software Engineer",
  "company": "Google",
  "type": "work",
  "startDate": "2023-09",
  "isCurrent": true,
  "location": "Mountain View, CA",
  "description": "Working on search infrastructure.",
  "tags": ["Go", "Distributed Systems", "Kubernetes"]
}` },
      { type: 'tip', content: 'Entries are sorted by start date. Use isCurrent: true for ongoing positions — they appear at the top. If a company name matches an entry in logos.json, its logo will be displayed.' },
    ],
  },
  {
    id: 'edit-research',
    icon: FaFlask,
    accent: '#b48ead',
    title: 'Edit Research Labs',
    subtitle: 'Current research affiliations shown on the About page',
    blocks: [
      { type: 'text', content: 'Edit content/research.json to list your research lab affiliations. Each lab is displayed on the About page with an icon and optional advisor.' },
      { type: 'fields', fields: [
        { name: 'lab', required: true, desc: 'Lab or research group name', example: 'AI Research Lab' },
        { name: 'emoji', required: true, desc: 'Fallback icon (shown if no logo image)', example: '🤖' },
        { name: 'advisor', desc: 'Advisor name (displayed as "w/ Prof. Name")' },
        { name: 'focus', required: true, desc: 'Research focus area', example: 'large language models' },
        { name: 'link', required: true, desc: 'Lab website URL' },
      ] },
      { type: 'code', label: 'Example research.json', content: `{
  "currentResearch": [
    {
      "lab": "AI Research Lab",
      "emoji": "🤖",
      "advisor": "Prof. Jane Smith",
      "focus": "large language models",
      "link": "https://ai-lab.edu"
    }
  ]
}` },
      { type: 'tip', content: 'If the lab name matches an entry in logos.json, the logo image is shown instead of the emoji.' },
    ],
  },
  {
    id: 'edit-news',
    icon: FaBullhorn,
    accent: '#ebcb8b',
    title: 'Edit News & Awards',
    subtitle: 'Announcements on the home page + awards list',
    blocks: [
      { type: 'text', content: 'Edit content/news.json for announcements and content/awards.json for awards. News items appear on the home page.' },
      { type: 'fields', fields: [
        { name: 'type', required: true, desc: 'Category: publication, talk, release, award', example: 'publication' },
        { name: 'badge', required: true, desc: 'Short label shown as a colored badge', example: 'Publication' },
        { name: 'icon', required: true, desc: 'React icon name for the badge', example: 'FaFileAlt' },
        { name: 'iconColor', desc: 'Chakra UI color for the icon', example: 'blue.400' },
        { name: 'title', required: true, desc: 'Headline of the news item' },
        { name: 'description', desc: 'Short description text' },
        { name: 'date', required: true, desc: 'Display date', example: 'Dec 2025' },
        { name: 'sortDate', required: true, desc: 'Sorting date (YYYY-MM-DD format)', example: '2025-12-01' },
        { name: 'links', desc: 'Optional action links (Paper, Code, etc.)' },
      ] },
      { type: 'text', content: 'Common icon names for news:' },
      { type: 'table', content: `Icon name|Looks like|Good for
FaFileAlt|Document|Publications, papers
FaMicrophone|Microphone|Talks, presentations
FaRocket|Rocket|Releases, launches
FaTrophy|Trophy|Awards, competitions
FaGraduationCap|Grad cap|Education milestones
FaCode|Code|Open source releases` },
      { type: 'text', content: 'Awards in content/awards.json use a simpler format:' },
      { type: 'fields', fields: [
        { name: 'title', required: true, desc: 'Award name', example: 'Best Paper Award' },
        { name: 'org', required: true, desc: 'Awarding organization', example: 'NeurIPS 2024' },
        { name: 'date', required: true, desc: 'Date received', example: 'Dec 2024' },
        { name: 'kind', required: true, desc: 'Type: grant, hackathon, travel, scholarship, honor, competition, innovation' },
        { name: 'link', desc: 'Optional link to the award page' },
      ] },
    ],
  },
  {
    id: 'about',
    icon: FaUser,
    accent: '#a3be8c',
    title: 'Edit About / Bio / Journey',
    subtitle: 'Your bio, career timeline, collaborators, and contact info',
    blocks: [
      { type: 'text', content: 'content/about.md has two parts: structured data (between --- marks) drives the Journey timeline, and the text below --- is your Bio narrative. These render as separate configurable sections on the home page.' },
      { type: 'fields', fields: [
        { name: 'Bio text (below ---)', desc: 'Your narrative bio — rendered by the "bio" section' },
        { name: 'journeyPhases', desc: 'Career timeline — rendered by the "journey" section' },
        { name: '  → period', required: true, desc: 'Time range', example: '2019 - 2023' },
        { name: '  → title', required: true, desc: 'Position or degree', example: 'B.S. in Computer Science' },
        { name: '  → org', required: true, desc: 'Organization name', example: 'UC Berkeley' },
        { name: '  → description', desc: 'Short description — supports **bold** markers' },
        { name: '  → tags', desc: 'Skill tags for this phase' },
        { name: 'mentorship', desc: 'Collaborators section — rendered by the "mentorship" section' },
      ] },
      { type: 'text', content: 'Additionally, these content files power their own sections:' },
      { type: 'fields', fields: [
        { name: 'talks.json', desc: 'Talks and presentations — each entry has title, event, date, type, slidesUrl, videoUrl' },
        { name: 'teaching.json', desc: 'Teaching entries — each has course, institution, semester, role, description' },
        { name: 'site.json → skills', desc: 'Skills section — use { name, icon } objects for icons, or plain strings' },
        { name: 'site.json → contact', desc: 'Contact section — auto-reads email, location, and social links' },
      ] },
      { type: 'code', label: 'Example about.md structure', content: `---
journeyPhases:
  - period: "2019 - 2023"
    title: B.S. in Computer Science
    org: UC Berkeley
    description: Studied **algorithms** and systems.
    tags: [Python, Algorithms]
  - period: "2023 - Present"
    title: Software Engineer
    org: Google
    description: Working on search infrastructure.
    tags: [Go, Systems]
mentorship:
  heading: Collaborators
  mentees:
    - name: Jane Smith
      url: https://janesmith.dev
      note: PhD student, co-author
---

Your narrative bio goes here. Write about yourself,
your research interests, and your goals.` },
      { type: 'code', label: 'Example talks.json', content: `[
  {
    "title": "My Invited Talk at ICML",
    "event": "ICML 2025",
    "date": "Jul 2025",
    "type": "invited",
    "slidesUrl": "https://...",
    "videoUrl": "https://..."
  }
]` },
      { type: 'code', label: 'Example teaching.json', content: `[
  {
    "course": "Intro to Machine Learning",
    "institution": "UC Berkeley",
    "semester": "Fall 2025",
    "role": "ta",
    "description": "Office hours and grading for 200+ students."
  }
]` },
      { type: 'tip', content: 'All these sections are independently orderable. Edit the "sections" array in site.json to reorder, add, or remove any section from the home page.' },
    ],
  },
  {
    id: 'images',
    icon: FaImage,
    accent: '#d08770',
    title: 'Images & Logos',
    subtitle: 'Where to put your photos, logos, and screenshots',
    blocks: [
      { type: 'text', content: 'All images live in content/images/ and are automatically served on your site. Here\'s how they\'re organized:' },
      { type: 'filetree', items: [
        { name: 'content/images/', isFolder: true, desc: 'All your images', depth: 0 },
        { name: 'avatar.jpg', desc: 'Your profile photo (set in site.json)', depth: 1 },
        { name: 'logos/', isFolder: true, desc: 'Institution and company logos', depth: 1 },
        { name: 'stanford.png', desc: 'Square PNG ~200x200px', depth: 2 },
        { name: 'publications/', isFolder: true, desc: 'Paper figures and thumbnails', depth: 1 },
        { name: 'my-paper-fig.png', desc: 'Referenced via featuredImage in publication .md', depth: 2 },
        { name: 'projects/', isFolder: true, desc: 'Project screenshots (optional)', depth: 1 },
      ] },
      { type: 'text', content: 'How to reference images in different files:' },
      { type: 'table', content: `File|How to reference|Example
site.json (avatar)|Just the filename|"avatar.jpg"
site.json (pets)|/images/ path|"/images/lulu.jpg"
logos.json|/images/logos/ path|"/images/logos/mit.png"
Markdown files|/images/ path|"/images/paper-fig.png"` },
      { type: 'text', content: 'Map institution names to logos in content/logos.json. The key must exactly match the institution name in experience.json or research.json.' },
      { type: 'code', label: 'Example logos.json', content: `{
  "Stanford University": "/images/logos/stanford.png",
  "Google": "/images/logos/google.png"
}` },
      { type: 'tip', content: 'Supported formats: .jpg, .png, .svg, .webp, .gif. For logos, square PNG or SVG at ~200x200px works best. For avatar, any aspect ratio works — it\'s displayed as a circle.' },
    ],
  },
  {
    id: 'commands',
    icon: FaTerminal,
    accent: '#81a1c1',
    title: 'Helpful Commands',
    subtitle: 'All the terminal commands you need',
    blocks: [
      { type: 'steps', steps: [
        { title: 'npm run dev', desc: 'Start the local dev server with hot reload — the main command you\'ll use.' },
        { title: 'npm run build', desc: 'Build your site for production. Output goes to the dist/ folder.' },
        { title: 'npm run setup', desc: 'Re-run the setup wizard to regenerate site.json from scratch.' },
        { title: 'npm run validate', desc: 'Check for common config mistakes like missing files or typos.' },
        { title: 'npm run lint', desc: 'Run the code linter to check for style issues.' },
      ] },
      { type: 'text', content: 'If something breaks, try these troubleshooting steps in order:' },
      { type: 'steps', steps: [
        { title: 'Run validate', desc: 'npm run validate — checks for config errors and missing files.' },
        { title: 'Clear cache and reinstall', desc: 'Delete node_modules and dist folders, then run npm install again.' },
        { title: 'Check TypeScript errors', desc: 'Run npx tsc --noEmit to see detailed error messages.' },
      ] },
      { type: 'tip', content: 'The dev server auto-refreshes when you save any file in content/. If it stops, just restart with npm run dev.' },
    ],
  },
  {
    id: 'deploy',
    icon: FaCloudUploadAlt,
    accent: '#88c0d0',
    title: 'Deploy Your Site',
    subtitle: 'Put your portfolio on the web — three easy options',
    blocks: [
      { type: 'text', content: 'After building your site, deploy it to the web. Here are three popular, free options:' },
      { type: 'steps', steps: [
        { title: 'GitHub Pages (recommended)', desc: 'Free and automatic. Push your code to GitHub, go to Settings → Pages → Source, select "GitHub Actions". Every push to main deploys automatically via the included workflow.' },
        { title: 'Vercel', desc: 'Easiest setup. Sign in at vercel.com with GitHub, click "Import Project", select your repo, and click "Deploy". Auto-detects Vite and deploys on every push.' },
        { title: 'Netlify', desc: 'Similar to Vercel. Sign in at netlify.com with GitHub, click "Add new site" → "Import from Git", select your repo, and deploy.' },
      ] },
      { type: 'text', content: 'Before deploying, always build locally first to catch errors:' },
      { type: 'code', label: 'Pre-deploy check', content: `# Build locally to catch errors
npm run build

# Check for common issues
npm run validate` },
      { type: 'tip', content: 'All three platforms support custom domains. Add your domain in the platform\'s settings and update your DNS records as instructed.' },
    ],
  },
  {
    id: 'mcp-server',
    icon: FaRobot,
    accent: '#88c0d0',
    title: 'AI Integration (MCP)',
    subtitle: 'Let AI generate your portfolio from a resume — powered by Model Context Protocol',
    blocks: [
      { type: 'text', content: 'TermHub includes a built-in MCP (Model Context Protocol) server that lets AI assistants like Claude directly read, write, and manage your portfolio content. Instead of editing files manually, you can give your resume to Claude and have it generate everything automatically.' },
      { type: 'steps', steps: [
        { title: 'Install the MCP server', desc: 'Navigate to the mcp-server/ directory inside TermHub and install its dependencies.' },
        { title: 'Configure your AI client', desc: 'Add the MCP server to Claude Desktop or Claude Code so the AI can use TermHub tools.' },
        { title: 'Talk to the AI', desc: 'Tell Claude to read your resume and generate your portfolio. It calls the tools automatically.' },
      ] },
      { type: 'code', label: 'Install MCP server', content: `# Install MCP server dependencies
cd mcp-server && npm install

# The server is built automatically after install
# Verify it works:
node dist/index.js --help` },
      { type: 'text', content: 'Configure the MCP server in your AI client:' },
      { type: 'code', label: 'Claude Desktop — add to claude_desktop_config.json', content: `{
  "mcpServers": {
    "termhub": {
      "command": "node",
      "args": ["/path/to/TermHub/mcp-server/dist/index.js"],
      "env": {
        "TERMHUB_ROOT": "/path/to/TermHub"
      }
    }
  }
}` },
      { type: 'code', label: 'Claude Code — .mcp.json already included in the project root', content: `{
  "mcpServers": {
    "termhub": {
      "command": "node",
      "args": ["mcp-server/dist/index.js"],
      "env": { "TERMHUB_ROOT": "." }
    }
  }
}` },
      { type: 'text', content: 'After configuring, restart your AI client. Then you can say things like:' },
      { type: 'code', label: 'Example prompts to Claude', content: `# Generate from resume PDF
"Parse my resume at ~/Desktop/resume.pdf and generate my portfolio."

# Generate from pasted text
"Here is my CV content: [paste text]. Generate all TermHub content."

# Add individual items
"Add a new publication: title is 'xxx', venue ACL 2025, I'm first author."
"Add a project: a web app called 'xxx' built with React and Node.js."

# Check status
"What content does my portfolio have right now?"` },
      { type: 'text', content: 'The MCP server exposes 22 tools. Here are the most commonly used ones:' },
      { type: 'table', content: `Tool|What it does
get_schema|Returns all data types — AI calls this first to understand the structure
get_site_status|Overview of current content (counts, profile info, active template)
list_templates|List available templates, component slots, and their variants
parse_pdf|Extract text from a PDF resume
generate_from_resume|All-in-one: creates a blueprint from resume text for AI to follow
update_site_config|Set name, email, social links, template, sections order
add_publication|Add a paper (with full metadata validation)
add_project|Add a project with tags, highlights, category
add_experience|Add a work/research timeline entry
add_education|Add an education entry
add_news|Add a news item
add_award|Add an award or honor
add_talk|Add a talk or presentation
add_teaching|Add a teaching entry
write_markdown_content|Write any Markdown content file
write_json_content|Write any JSON content file (including talks, teaching)
manage_assets|Copy images (avatar, logos) to the right directories
preview_site|Start dev server or build for production
reset_content|Clear all content for a fresh start` },
      { type: 'tip', content: 'The typical AI workflow is: parse_pdf → generate_from_resume → reset_content → call individual add_* tools for each item → preview_site. The whole process takes under a minute.' },
    ],
  },
  {
    id: 'faq',
    icon: FaQuestionCircle,
    accent: '#b48ead',
    title: 'FAQ & Troubleshooting',
    subtitle: 'Common questions and quick solutions',
    blocks: [
      { type: 'fields', fields: [
        { name: 'Site didn\'t update after saving?', desc: 'Check that the dev server is still running in your terminal. If it crashed, restart with npm run dev.' },
        { name: 'Red error in the terminal?', desc: 'Usually a typo in JSON — missing comma, extra comma, unclosed quotes. Run npm run validate to find the issue.' },
        { name: 'Avatar or logo not showing?', desc: 'Make sure the file is in content/images/ and the filename matches exactly (case-sensitive). Check avatar field in site.json or key in logos.json.' },
        { name: 'How to reorder home page sections?', desc: 'Edit the "sections" array in site.json. Remove a section name to hide it, reorder to change display order.' },
        { name: 'How to switch component variants?', desc: 'Set "components": { "hero": "minimal" } in site.json. Use the MCP list_templates tool to see available variants.' },
        { name: 'How to add icons to skills?', desc: 'Change skills from strings to objects: { "name": "Python", "icon": "FaPython" }. Icons use react-icons names.' },
        { name: 'How to change colors/theme?', desc: 'Edit src/config/theme.ts — this requires some code knowledge. The file has comments explaining each color.' },
        { name: 'How to add a new page?', desc: 'Requires code changes: create a component in src/components/, add a route in src/App.tsx, and add to navItems in src/site.config.ts.' },
        { name: 'Not a researcher?', desc: 'No problem! Disable publications and research in site.json, focus on projects and articles. TermHub works great for developers, designers, students, and anyone who wants a clean portfolio.' },
      ] },
    ],
  },
]

/* ── Helper: file extension → color ─────────────────────────── */

const fileColor = (name: string): string => {
  if (name.endsWith('.json')) return '#ebcb8b'
  if (name.endsWith('.md')) return '#a3be8c'
  if (name.endsWith('.jpg') || name.endsWith('.png') || name.endsWith('.svg')) return '#d08770'
  return '#81a1c1'
}

/* ── GuideDocs Component ──────────────────────────────────────── */

const GuideDocs: React.FC = () => {
  const { colorMode } = useColorMode()
  const isDark = colorMode === 'dark'
  const location = useLocation()
  const navigate = useNavigate()
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({ quickstart: true })
  const [activeSection, setActiveSection] = useState('quickstart')
  const [expandedCode, setExpandedCode] = useState<Record<string, boolean>>({})

  const tc = terminalPalette.colors(isDark)
  const cardBg = useColorModeValue('white', 'gray.800')
  const borderColor = useColorModeValue('gray.200', 'gray.700')
  const subtitleColor = useColorModeValue('gray.500', 'gray.400')
  const pageBg = useColorModeValue('gray.50', 'gray.900')
  const mutedText = useColorModeValue('gray.600', 'gray.300')
  const headingColor = useColorModeValue('gray.800', 'gray.50')

  /* Scroll to hash section on mount (from landing page links) */
  useEffect(() => {
    const hash = location.hash.replace('#', '')
    if (hash) {
      setExpandedSections(prev => ({ ...prev, [hash]: true }))
      setActiveSection(hash)
      setTimeout(() => {
        document.getElementById(`guide-${hash}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }, 100)
    }
  }, [location.hash])

  const toggleSection = (id: string) => {
    setExpandedSections(prev => ({ ...prev, [id]: !prev[id] }))
    setActiveSection(id)
  }

  const toggleCode = (key: string) => {
    setExpandedCode(prev => ({ ...prev, [key]: !prev[key] }))
  }

  /* Current section accent */
  const getAccent = (sectionId: string) =>
    sections.find(s => s.id === sectionId)?.accent ?? '#88c0d0'

  /* ── Render helpers ─────────────────────────────────────────── */

  const renderSteps = (steps: { title: string; desc: string }[], accent: string) => (
    <VStack align="stretch" spacing={0} position="relative">
      {/* Connecting line */}
      <Box
        position="absolute"
        left="17px"
        top="22px"
        bottom="22px"
        w="2px"
        bg={`${accent}30`}
        borderRadius="full"
      />
      {steps.map((step, i) => (
        <Flex key={i} gap={4} align="flex-start" py={3} position="relative">
          <Flex
            w="34px" h="34px" borderRadius="full" flexShrink={0}
            bg={`${accent}18`}
            border="2px solid"
            borderColor={accent}
            color={accent}
            align="center" justify="center"
            fontSize="sm" fontWeight="bold"
            zIndex={1}
            boxShadow={`0 0 0 4px ${isDark ? '#1a202c' : '#f7fafc'}`}
          >
            {i + 1}
          </Flex>
          <Box flex={1} pt={1}>
            <Text fontSize="sm" fontWeight="700" color={headingColor}>
              {step.title}
            </Text>
            <Text fontSize="sm" color={mutedText} lineHeight="1.7" mt={1}>
              {step.desc}
            </Text>
          </Box>
        </Flex>
      ))}
    </VStack>
  )

  const renderFields = (fields: { name: string; required?: boolean; desc: string; example?: string }[], accent: string) => (
    <VStack align="stretch" spacing={2}>
      {fields.map((f, i) => {
        const isNested = f.name.startsWith('  ')
        return (
          <Box
            key={i}
            bg={isDark ? `${accent}08` : `${accent}06`}
            borderRadius="lg"
            px={4} py={3}
            borderLeft="3px solid"
            borderLeftColor={f.required ? accent : (isDark ? 'gray.600' : 'gray.300')}
            ml={isNested ? 4 : 0}
            transition="all 0.15s"
            _hover={{ bg: isDark ? `${accent}12` : `${accent}0a`, transform: 'translateX(2px)' }}
          >
            <Flex align="center" gap={2} flexWrap="wrap">
              <Text fontSize="sm" fontWeight="700" fontFamily="mono" color={accent}>
                {f.name.trim()}
              </Text>
              {f.required && (
                <Badge
                  fontSize="2xs" px={1.5} py={0.5} borderRadius="full"
                  bg={`${accent}20`} color={accent}
                  fontWeight="bold" textTransform="uppercase"
                  letterSpacing="wider"
                >
                  required
                </Badge>
              )}
            </Flex>
            <Text fontSize="sm" color={mutedText} mt={1.5} lineHeight="1.7">
              {f.desc}
            </Text>
            {f.example && (
              <Flex mt={2} align="center" gap={2}>
                <Text fontSize="xs" color={subtitleColor} fontWeight="600">Example:</Text>
                <Text
                  fontSize="xs" fontFamily="mono"
                  bg={isDark ? 'whiteAlpha.100' : 'blackAlpha.50'}
                  px={2} py={0.5} borderRadius="md"
                  color={isDark ? 'gray.200' : 'gray.700'}
                >
                  {f.example}
                </Text>
              </Flex>
            )}
          </Box>
        )
      })}
    </VStack>
  )

  const renderFileTree = (items: { name: string; isFolder?: boolean; desc?: string; depth: number }[]) => (
    <Box
      borderRadius="lg"
      overflow="hidden"
      border="1px solid"
      borderColor={borderColor}
    >
      {items.map((item, i) => {
        const color = item.isFolder ? '#ebcb8b' : fileColor(item.name)
        return (
          <Flex
            key={i}
            px={4} py={2.5}
            pl={`${16 + item.depth * 24}px`}
            align="center" gap={3}
            borderBottom={i < items.length - 1 ? '1px solid' : 'none'}
            borderBottomColor={isDark ? 'gray.700' : 'gray.100'}
            bg={isDark
              ? (i % 2 === 0 ? 'gray.800' : 'gray.750')
              : (i % 2 === 0 ? 'white' : 'gray.50')
            }
            _hover={{ bg: isDark ? `${color}10` : `${color}08` }}
            transition="background 0.15s"
          >
            <Icon
              as={item.isFolder ? FaFolder : FaFile}
              boxSize={3.5}
              color={color}
              flexShrink={0}
            />
            <Text
              fontSize="sm" fontFamily="mono"
              fontWeight={item.isFolder ? 'bold' : 'normal'}
              color={headingColor}
            >
              {item.name}
            </Text>
            {item.desc && (
              <Text fontSize="xs" color={subtitleColor} ml="auto" flexShrink={0} pl={4}>
                {item.desc}
              </Text>
            )}
          </Flex>
        )
      })}
    </Box>
  )

  const renderToggles = (toggles: { name: string; desc: string; default: boolean }[]) => (
    <Grid templateColumns={['1fr', '1fr 1fr']} gap={3}>
      {toggles.map((t, i) => (
        <Flex
          key={i}
          bg={isDark
            ? (t.default ? 'rgba(163,190,140,0.06)' : 'rgba(191,97,106,0.04)')
            : (t.default ? 'rgba(163,190,140,0.06)' : 'rgba(191,97,106,0.03)')
          }
          borderRadius="lg"
          px={4} py={3}
          align="center"
          gap={3}
          border="1px solid"
          borderColor={t.default
            ? (isDark ? 'rgba(163,190,140,0.2)' : 'rgba(163,190,140,0.25)')
            : (isDark ? 'rgba(191,97,106,0.15)' : 'rgba(191,97,106,0.12)')
          }
          transition="all 0.15s"
          _hover={{ transform: 'translateY(-1px)', boxShadow: 'sm' }}
        >
          <Flex
            w="36px" h="20px" borderRadius="full"
            bg={t.default ? '#a3be8c' : (isDark ? 'gray.600' : 'gray.300')}
            align="center"
            justify={t.default ? 'flex-end' : 'flex-start'}
            px="2px"
            flexShrink={0}
            transition="background 0.2s"
            boxShadow="inset 0 1px 3px rgba(0,0,0,0.15)"
          >
            <Box w="16px" h="16px" borderRadius="full" bg="white" boxShadow="sm" />
          </Flex>
          <Box flex={1} minW={0}>
            <Text fontSize="sm" fontWeight="700" color={headingColor}>
              {t.name}
            </Text>
            <Text fontSize="xs" color={mutedText} mt={0.5} lineHeight="1.5">
              {t.desc}
            </Text>
          </Box>
        </Flex>
      ))}
    </Grid>
  )

  const renderCodeBlock = (code: string, label: string | undefined, blockKey: string) => {
    const isOpen = expandedCode[blockKey] ?? false
    return (
      <Box
        borderRadius="lg"
        overflow="hidden"
        border="1px solid"
        borderColor={isOpen ? tc.border : borderColor}
        transition="border-color 0.2s"
      >
        <Flex
          as="button"
          w="full"
          px={4} py={2.5}
          bg={isDark ? 'rgba(136,192,208,0.06)' : 'rgba(94,129,172,0.04)'}
          align="center"
          justify="space-between"
          onClick={() => toggleCode(blockKey)}
          _hover={{ bg: isDark ? 'rgba(136,192,208,0.1)' : 'rgba(94,129,172,0.07)' }}
          transition="background 0.15s"
        >
          <HStack spacing={2.5}>
            <Flex
              w="24px" h="24px" borderRadius="md"
              bg={isDark ? 'rgba(136,192,208,0.12)' : 'rgba(94,129,172,0.1)'}
              align="center" justify="center"
            >
              <Icon as={FaCode} boxSize={2.5} color={tc.command} />
            </Flex>
            <Text fontSize="sm" color={isDark ? 'gray.300' : 'gray.600'} fontWeight="600">
              {label || 'View code example'}
            </Text>
          </HStack>
          <Icon
            as={FaChevronDown}
            boxSize={3}
            color={subtitleColor}
            transform={isOpen ? 'rotate(180deg)' : 'rotate(0deg)'}
            transition="transform 0.2s"
          />
        </Flex>
        <Collapse in={isOpen} animateOpacity>
          <Box bg={tc.bg} borderTop={`1px solid ${tc.border}`}>
            {/* Mini traffic lights */}
            <Flex px={3} py={1.5} gap={1.5} borderBottom={`1px solid ${tc.border}`}>
              <Box w="7px" h="7px" borderRadius="full" bg="#bf616a" />
              <Box w="7px" h="7px" borderRadius="full" bg="#ebcb8b" />
              <Box w="7px" h="7px" borderRadius="full" bg="#a3be8c" />
            </Flex>
            <Box
              px={4} py={3}
              fontSize="xs"
              overflowX="auto"
              whiteSpace="pre"
              lineHeight="2"
              fontFamily="mono"
            >
              {code.split('\n').map((line, i) => {
                const isComment = line.trimStart().startsWith('#') || line.trimStart().startsWith('//')
                const isArrow = line.includes('←')
                const parts = isArrow ? line.split('←') : [line]

                return (
                  <Box key={i}>
                    {isComment ? (
                      <Text as="span" color={tc.secondary}>{line}</Text>
                    ) : isArrow ? (
                      <>
                        <Text as="span" color={tc.text}>{parts[0]}</Text>
                        <Text as="span" color={tc.secondary}>← {parts.slice(1).join('←')}</Text>
                      </>
                    ) : (
                      <Text as="span" color={tc.text}>{line}</Text>
                    )}
                  </Box>
                )
              })}
            </Box>
          </Box>
        </Collapse>
      </Box>
    )
  }

  const renderTable = (content: string, accent: string) => {
    const rows = content.trim().split('\n')
    const headers = rows[0].split('|')
    const data = rows.slice(1).map(r => r.split('|'))

    return (
      <Box
        borderRadius="lg"
        overflow="hidden"
        border="1px solid"
        borderColor={borderColor}
      >
        <Flex
          bg={`${accent}15`}
          px={4} py={2.5}
          borderBottom="2px solid"
          borderBottomColor={`${accent}40`}
          fontWeight="bold"
          gap={0}
        >
          {headers.map((h, i) => (
            <Box key={i} flex={i === headers.length - 1 ? 2 : 1}>
              <Text fontSize="xs" fontWeight="800" color={accent} textTransform="uppercase" letterSpacing="wider">
                {h.trim()}
              </Text>
            </Box>
          ))}
        </Flex>
        {data.map((row, ri) => (
          <Flex
            key={ri}
            px={4} py={2.5}
            borderBottom={ri < data.length - 1 ? '1px solid' : 'none'}
            borderBottomColor={isDark ? 'gray.700' : 'gray.100'}
            bg={isDark
              ? (ri % 2 === 0 ? 'transparent' : 'whiteAlpha.50')
              : (ri % 2 === 0 ? 'transparent' : 'gray.50')
            }
            _hover={{ bg: isDark ? `${accent}08` : `${accent}06` }}
            transition="background 0.1s"
            gap={0}
          >
            {row.map((cell, ci) => (
              <Box key={ci} flex={ci === row.length - 1 ? 2 : 1}>
                <Text
                  fontSize="sm"
                  fontWeight={ci === 0 ? '600' : 'normal'}
                  fontFamily={ci === 0 ? 'mono' : 'body'}
                  color={ci === 0 ? accent : mutedText}
                >
                  {cell.trim()}
                </Text>
              </Box>
            ))}
          </Flex>
        ))}
      </Box>
    )
  }

  const renderTip = (text: string) => (
    <Flex
      bg={isDark ? 'rgba(163,190,140,0.06)' : 'rgba(163,190,140,0.06)'}
      border="1px solid"
      borderColor={isDark ? 'rgba(163,190,140,0.2)' : 'rgba(163,190,140,0.2)'}
      borderLeft="3px solid"
      borderLeftColor="#a3be8c"
      borderRadius="lg"
      px={4} py={3.5}
      align="flex-start"
      gap={3}
    >
      <Flex
        w="24px" h="24px" borderRadius="full"
        bg="rgba(163,190,140,0.15)"
        align="center" justify="center"
        flexShrink={0} mt={0.5}
      >
        <Icon as={FaLightbulb} color="#a3be8c" boxSize={3} />
      </Flex>
      <Box>
        <Text fontSize="xs" fontWeight="800" color="#a3be8c" textTransform="uppercase" letterSpacing="wider" mb={1}>
          Tip
        </Text>
        <Text fontSize="sm" color={mutedText} lineHeight="1.8">{text}</Text>
      </Box>
    </Flex>
  )

  const renderBlock = (block: Block, sectionId: string, blockIndex: number) => {
    const blockKey = `${sectionId}-${blockIndex}`
    const accent = getAccent(sectionId)

    switch (block.type) {
      case 'text':
        return <Text fontSize="sm" color={mutedText} lineHeight="1.9">{block.content}</Text>
      case 'code':
        return renderCodeBlock(block.content, block.label, blockKey)
      case 'table':
        return renderTable(block.content, accent)
      case 'tip':
        return renderTip(block.content)
      case 'steps':
        return renderSteps(block.steps, accent)
      case 'fields':
        return renderFields(block.fields, accent)
      case 'filetree':
        return renderFileTree(block.items)
      case 'toggles':
        return renderToggles(block.toggles)
      default:
        return null
    }
  }

  return (
    <Box w="full" minH="100vh" bg={pageBg} py={8}>
      <Container maxW="5xl" px={[3, 4, 6]}>

        {/* Back to landing */}
        <Flex
          as="button"
          onClick={() => navigate('/guide')}
          align="center"
          gap={2}
          mb={6}
          fontSize="sm"
          color={tc.command}
          _hover={{ opacity: 0.8, transform: 'translateX(-2px)' }}
          transition="all 0.15s"
        >
          <Icon as={FaArrowLeft} boxSize={3} />
          Back to Guide
        </Flex>

        {/* Page header */}
        <Box mb={10}>
          <Image
            src={`${import.meta.env.BASE_URL}logo.svg`}
            alt="TermHub"
            h={['56px', '72px']}
            objectFit="contain"
            mb={5}
          />
          <Heading as="h1" fontSize={['2xl', '3xl']} fontWeight="800" color={headingColor} mb={2}>
            Full Documentation
          </Heading>
          <Text fontSize="md" color={subtitleColor} maxW="600px" lineHeight="1.7">
            Step-by-step visual guides for every content file — expand any section to learn more.
          </Text>
          <Flex mt={4} gap={2} flexWrap="wrap">
            <Badge px={2.5} py={1} borderRadius="full" bg="rgba(136,192,208,0.12)" color="#88c0d0" fontSize="xs" fontWeight="600">
              {sections.length} Sections
            </Badge>
            <Badge px={2.5} py={1} borderRadius="full" bg="rgba(163,190,140,0.12)" color="#a3be8c" fontSize="xs" fontWeight="600">
              Beginner Friendly
            </Badge>
            <Badge px={2.5} py={1} borderRadius="full" bg="rgba(180,142,173,0.12)" color="#b48ead" fontSize="xs" fontWeight="600">
              No Code Required
            </Badge>
          </Flex>

          {/* No-code alternative */}
          <Flex
            mt={5}
            bg={isDark ? 'rgba(136,192,208,0.06)' : 'rgba(136,192,208,0.08)'}
            border={`1px solid ${isDark ? 'rgba(136,192,208,0.15)' : 'rgba(136,192,208,0.2)'}`}
            borderRadius="md"
            px={4} py={3}
            align="center"
            justify="space-between"
            flexWrap="wrap"
            gap={3}
          >
            <HStack spacing={2} flex={1}>
              <Text fontSize="xs" color={tc.command} fontWeight="bold" fontFamily="mono" flexShrink={0}>TIP</Text>
              <Text fontSize="xs" color={mutedText} lineHeight="1.7">
                <Text as="span" fontWeight="bold">Don&apos;t want to set up a dev environment?</Text>
                {' '}We also offer a hosted solution — just upload your resume and get a live portfolio. No Git, no terminal, no coding required.
              </Text>
            </HStack>
            <Flex
              as="a"
              href="https://termhubai.com"
              target="_blank"
              rel="noopener noreferrer"
              bg={tc.command}
              color="white"
              px={4} py={1.5}
              borderRadius="md"
              fontWeight="semibold"
              fontSize="xs"
              align="center"
              gap={1.5}
              _hover={{ opacity: 0.85 }}
              transition="all 0.2s"
              flexShrink={0}
            >
              <Icon as={FaGlobe} boxSize={3} />
              termhubai.com
            </Flex>
          </Flex>
        </Box>

        <Grid templateColumns={['1fr', '1fr', '230px 1fr']} gap={8}>

          {/* ═══ Sidebar TOC ═══ */}
          <GridItem display={['none', 'none', 'block']}>
            <Box position="sticky" top="80px">
              <Text fontSize="xs" fontWeight="800" color={subtitleColor} textTransform="uppercase" letterSpacing="wider" mb={4}>
                Contents
              </Text>
              <VStack align="stretch" spacing={1}>
                {sections.map((s) => (
                  <Flex
                    key={s.id}
                    as="button"
                    onClick={() => {
                      setExpandedSections(prev => ({ ...prev, [s.id]: true }))
                      setActiveSection(s.id)
                      document.getElementById(`guide-${s.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
                    }}
                    px={3}
                    py={2}
                    fontSize="sm"
                    borderRadius="lg"
                    align="center"
                    gap={2.5}
                    bg={activeSection === s.id ? `${s.accent}12` : 'transparent'}
                    color={activeSection === s.id ? s.accent : subtitleColor}
                    borderLeft="3px solid"
                    borderLeftColor={activeSection === s.id ? s.accent : 'transparent'}
                    _hover={{ color: s.accent, bg: `${s.accent}08` }}
                    transition="all 0.15s"
                    textAlign="left"
                  >
                    <Icon as={s.icon} boxSize={3} flexShrink={0} />
                    <Text noOfLines={1} fontWeight={activeSection === s.id ? '600' : 'normal'}>{s.title}</Text>
                  </Flex>
                ))}
              </VStack>
            </Box>
          </GridItem>

          {/* ═══ Mobile TOC ═══ */}
          <GridItem display={['block', 'block', 'none']} colSpan={1}>
            <Box
              bg={cardBg}
              border="1px solid"
              borderColor={borderColor}
              borderRadius="xl"
              px={4} py={3}
              mb={2}
              boxShadow="sm"
            >
              <Text fontSize="xs" fontWeight="800" color={subtitleColor} textTransform="uppercase" letterSpacing="wider" mb={3}>
                Contents
              </Text>
              <Flex flexWrap="wrap" gap={1.5}>
                {sections.map((s) => (
                  <Flex
                    key={s.id}
                    as="button"
                    onClick={() => {
                      setExpandedSections(prev => ({ ...prev, [s.id]: true }))
                      setActiveSection(s.id)
                      document.getElementById(`guide-${s.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
                    }}
                    px={2.5} py={1.5}
                    fontSize="xs"
                    borderRadius="lg"
                    bg={activeSection === s.id ? `${s.accent}15` : 'transparent'}
                    color={activeSection === s.id ? s.accent : subtitleColor}
                    border="1px solid"
                    borderColor={activeSection === s.id ? `${s.accent}30` : 'transparent'}
                    _hover={{ color: s.accent }}
                    transition="all 0.15s"
                    gap={1.5}
                    align="center"
                    fontWeight={activeSection === s.id ? '600' : 'normal'}
                  >
                    <Icon as={s.icon} boxSize={2.5} />
                    <Text>{s.title}</Text>
                  </Flex>
                ))}
              </Flex>
            </Box>
          </GridItem>

          {/* ═══ Main content ═══ */}
          <GridItem>
            <VStack spacing={5} align="stretch">
              {sections.map((section) => (
                <Box
                  key={section.id}
                  id={`guide-${section.id}`}
                  bg={cardBg}
                  border="1px solid"
                  borderColor={expandedSections[section.id] ? `${section.accent}50` : borderColor}
                  borderRadius="xl"
                  overflow="hidden"
                  transition="all 0.2s"
                  boxShadow={expandedSections[section.id] ? `0 4px 20px ${section.accent}10` : 'sm'}
                >
                  {/* Section header */}
                  <Flex
                    as="button"
                    w="full"
                    px={5}
                    py={4}
                    align="center"
                    justify="space-between"
                    onClick={() => toggleSection(section.id)}
                    _hover={{ bg: isDark ? `${section.accent}06` : `${section.accent}04` }}
                    transition="background 0.15s"
                    textAlign="left"
                  >
                    <HStack spacing={3.5}>
                      <Flex
                        w="40px" h="40px" borderRadius="xl" flexShrink={0}
                        bg={`${section.accent}15`}
                        align="center" justify="center"
                        boxShadow={`0 2px 8px ${section.accent}20`}
                      >
                        <Icon as={section.icon} boxSize={4} color={section.accent} />
                      </Flex>
                      <Box>
                        <Heading as="h3" fontSize="md" fontWeight="700" color={headingColor}>
                          {section.title}
                        </Heading>
                        <Text fontSize="sm" color={subtitleColor} mt={0.5}>
                          {section.subtitle}
                        </Text>
                      </Box>
                    </HStack>
                    <Flex
                      w="28px" h="28px" borderRadius="full" flexShrink={0}
                      bg={expandedSections[section.id] ? `${section.accent}15` : 'transparent'}
                      align="center" justify="center"
                      transition="all 0.2s"
                    >
                      <Icon
                        as={FaChevronDown}
                        color={expandedSections[section.id] ? section.accent : subtitleColor}
                        boxSize={3}
                        transform={expandedSections[section.id] ? 'rotate(180deg)' : 'rotate(0deg)'}
                        transition="transform 0.2s"
                      />
                    </Flex>
                  </Flex>

                  {/* Accent strip when expanded */}
                  {expandedSections[section.id] && (
                    <Box h="2px" bg={`linear-gradient(90deg, ${section.accent}, ${section.accent}40, transparent)`} />
                  )}

                  {/* Section content */}
                  <Collapse in={expandedSections[section.id]} animateOpacity>
                    <VStack
                      align="stretch"
                      spacing={5}
                      px={5}
                      pb={6}
                      pt={4}
                    >
                      {section.blocks.map((block, bi) => (
                        <Box key={bi}>
                          {renderBlock(block, section.id, bi)}
                        </Box>
                      ))}
                    </VStack>
                  </Collapse>
                </Box>
              ))}
            </VStack>
          </GridItem>
        </Grid>
      </Container>
    </Box>
  )
}

export default GuideDocs
